### ISSUE TITLE
Glami.cz - XML feed

### ISSUE THREAD

**Issue by pavelevap** [pavelevap/ceske-sluzby#169]
https://info.glami.cz/feed/

**Comment by pavelevap** [comment]
Hlavní (zatím nalezené) rozdíly:
- [ ] Vyprodané produkty se ve feedu vůbec neuvádí.
- [ ] V názvech produktů nesmí být uvedena velikost ani barva, takže tam nebudeme uvádět parametry v `PRODUCTNAME`?
- [ ] Uvádět podrobné kategorie přímo z webu, ale na prvním místě by mělo být vždy uvedeno Ženy/Muži
- [ ] `PRODUCTNO` bude `SKU`?
- [ ] Bude třeba doplnit `DELIVERY` elementy (i když jsou nepovinné), nemají to někde nastavitelné přímo v administraci jako Heureka?
- [ ] Možnost odfiltrovat obrázky s logy a vodoznaky (ruční označení uživatelem)?

**Comment by lukasprelovsky** [comment]
Mam k dispozicii test eshop primo pro glami (ostra verze) takze budeme moci testovat.

**Comment by pavelevap** [comment]
@lukasprelovsky: Definoval jsem základní rozdíly, zkusíš to naimportovat? :-) Asi tam budou nějaké problémy, postupně je budeme odstraňovat...

**Comment by lukasprelovsky** [comment]
Ahoj, pouzivam php 7.1 a ceske sluzby nova verze s glami nefunguje tady je php error notice

Notice: Trying to get property of non-object in /nfsmnt/hosting2_1/0/7/076e6cf9-20d9-4832-b3fb-116505269eec/xxxxxxxx.sk/web/wp-content/plugins/woo-doprava/classes/class-platba-na-ucet.php on line 265

Notice: Trying to get property of non-object in /nfsmnt/hosting2_1/0/7/076e6cf9-20d9-4832-b3fb-116505269eec/xxxxxxxx.sk/web/wp-content/plugins/woo-doprava/classes/class-wc-gateway-dobirka.php on line 379

Fatal error: Uncaught Error: Call to a member function get() on null in /nfsmnt/hosting2_1/0/7/076e6cf9-20d9-4832-b3fb-116505269eec/xxxxxxxx.sk/web/wp-content/plugins/woo-doprava/classes/class-vyzvednuti-na-miste.php:173 Stack trace: #0 /nfsmnt/hosting2_1/0/7/076e6cf9-20d9-4832-b3fb-116505269eec/xxxxxxxx.sk/web/wp-content/plugins/ceske-sluzby/includes/class-ceske-sluzby-admin.php(27): WC_Gateway_VZNM->is_available() #1 /nfsmnt/hosting2_1/0/7/076e6cf9-20d9-4832-b3fb-116505269eec/xxxxxxxx.sk/web/wp-content/plugins/ceske-sluzby/includes/class-ceske-sluzby-admin.php(426): WC_Settings_Tab_Ceske_Sluzby_Admin::ceske_sluzby_ziskat_aktivovane_platebni_metody() #2 /nfsmnt/hosting2_1/0/7/076e6cf9-20d9-4832-b3fb-116505269eec/xxxxxxxx.sk/web/wp-includes/class-wp-hook.php(298): WC_Settings_Tab_Ceske_Sluzby_Admin::ceske_sluzby_nastaveni_pokladna_doprava('') #3 /nfsmnt/hosting2_1/0/7/076e6cf9-20d9-4832-b3fb-116505269eec/xxxxxxxx.sk/web/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array) #4 /nfsmnt/hosting2_1/0/7/076e6cf9-2 in /nfsmnt/hosting2_1/0/7/076e6cf9-20d9-4832-b3fb-116505269eec/xxxxxxxx.sk/web/wp-content/plugins/woo-doprava/classes/class-vyzvednuti-na-miste.php on line 173

**Comment by lukasprelovsky** [comment]
pouziva se woo 2.6.14

**Comment by pavelevap** [comment]
To vypadá spíše na nějaký problém s pluginem Woo Doprava? Máš tam asi aktivní nějakou možnost "vyzvednutí na místě" a když se dotážu, zda je tato možnost dostupná pomocí standardní metody `is_available()`, tak to umře. Ale nevím, ten plugin jsem nikdy neviděl, takže nevím, co to může způsobovat.

**Comment by pavelevap** [comment]
Těžko ale říci, kde je přesně příčina, nemohl bys to zkusit na nějakém čistém testovacím webu a dát mi přístupy?

**Comment by lukasprelovsky** [comment]
Ahoj, woo doprava ma license key, takze to asi na subdomene nenasimuluji. :(

Muzu ale se Musildu zeptat jestli mi nepujci na testy

**Comment by pavelevap** [comment]
Co to je vlastně to vyzvednutí na místě? Doprava nebo platební metoda?

Zkus dát místo tohoto [řádku](https://github.com/pavelevap/ceske-sluzby/blob/master/includes/class-ceske-sluzby-admin.php#L27):

`if ( $gateway->is_available() || ( isset( $gateway->enabled ) && $gateway->enabled == 'yes' ) ) {`

toto:

`if ( ! empty( $gateway ) && ( $gateway->is_available() || ( isset( $gateway->enabled ) && $gateway->enabled == 'yes' ) ) ) {`

**Comment by lukasprelovsky** [comment]
Po tyhle zmene:

funguje web
funguje xml glami
funguje heureka

nefunguje administrace - white page + zapnute php notice a zadny error neukazuje

**Comment by pavelevap** [comment]
Ani v logu nic není? Tam musí být nějaký fatal error...

**Comment by lukasprelovsky** [comment]
Notice:  Constant EMPTY_TRASH_DAYS already defined in /nfsmnt/hosting2_1/0/7/076e6cf9-20d9-4832-b3fb-116505269eec/xxxxxxxxx.sk/web/wp-config.php on line 91, referer https://xxxxxxxxx.sk/wp-admin/
xxxxxxxxx.sk [Tue May 23 13:50:36.425019 2017] [-:error] [pid 44739] [client 213.160.163.77:48172] PHP Warning:  Declaration of WC_Shipping_Ceske_Sluzby_Ulozenka::calculate_shipping($package) should be compatible with WC_Shipping_Method::calculate_shipping($package = Array) in /nfsmnt/hosting2_1/0/7/076e6cf9-20d9-4832-b3fb-116505269eec/xxxxxxxxx.sk/web/wp-content/plugins/ceske-sluzby/includes/class-ceske-sluzby-ulozenka.php on line 99, referer https://xxxxxxxxx.sk/produkt/mayoral-1805-saty-celenka/
xxxxxxxxx.sk [Tue May 23 13:50:36.425568 2017] [-:error] [pid 44739] [client 213.160.163.77:48172] PHP Warning:  Declaration of WC_Shipping_Ceske_Sluzby_DPD_ParcelShop::calculate_shipping($package) should be compatible with WC_Shipping_Method::calculate_shipping($package = Array) in /nfsmnt/hosting2_1/0/7/076e6cf9-20d9-4832-b3fb-116505269eec/xxxxxxxxx.sk/web/wp-content/plugins/ceske-sluzby/includes/class-ceske-sluzby-dpd-parcelshop.php on line 92, referer https://xxxxxxxxx.sk/produkt/mayoral-1805-saty-celenka/

**Comment by pavelevap** [comment]
To jsou jen Warningy, to by nemělo způsobit bílou stránku, podivné... Koukal jsem na nějaké video k pluginu Woo doprava a je to dost specifický plugin, takže ho asi budu muset nějak odfiltrovat, když bude na webu aktivní. Jestli můžeš, tak udělej prosím nějaký testovací web (kopie webu třeba na subdoméně). Když to nebude fungovat kvůli licenci, tak ji tam případně dočasně odpojím :wink:

**Comment by lukasprelovsky** [comment]
Odstraneno aktualizacii woo doprava, byla to chyba pluginu uz je to fixnuty (koukal jsem changelog + pridal aktualizacii) a uz to facha :))

Muzem pokracovat.. Jdu to pridat do glami a budu hlasit co je spatne.

**Comment by lukasprelovsky** [comment]
Zatim vidim neduhy tady:

Zatim koukam a bude treba z feedu zmazat velikost produktu v PRODUCTNAME.

Jinak nevidim nic co by bylo spatne.

**Comment by pavelevap** [comment]
Přidáno nastavení kategorií, uvidíme, zda to k něčemu bude, možná bude potřeba ještě nějak podpořit varianty (když je eshop používá k rozlišení Muži/Ženy).

**Comment by lukasprelovsky** [comment]
Ted je feed asi lepsi, protoze ukazuje mene nedostatku :))

![cek](https://cloud.githubusercontent.com/assets/15073394/26515180/74347034-4278-11e7-8134-97ba666e971e.png)

Asi pres 30 kategorii jsem rucne skategorizoval s glami, uvidime kdyz se updatne u nich feed jak mi sparuje produkty :)

**Comment by lukasprelovsky** [comment]
Kategorie jsem zaradil vsechny, ale porad cekam na odpoved Glami. Uz 3 dni meskaji s odpovedi.

**Comment by lukasprelovsky** [comment]
Na emaily neodpovidaji, ale volal jsem tam a chyby nam tam DELIVERY_PRICE. Vice chyb nenasli.

<DELIVERY>
<DELIVERY_ID>Česká pošta</DELIVERY_ID>
<DELIVERY_PRICE>59</DELIVERY_PRICE>
<DELIVERY_PRICE_COD>99</DELIVERY_PRICE_COD>
</DELIVERY>

ve feedu mame jenom delivery_date

**Comment by lukasprelovsky** [comment]
Podrobna kategorizace - pres tel mi ten pan rikal ze ten jejich system to nejak moc dobre nereflektuje, takze i kdyz mate vyplneny vsechny kategorie spravne tak to system porad ukazuje ako ze feed neni 100% a chyby dukladne zarazeni kategorii. Pan ze supportu mi oznacil manualne feed ako OK, co je dost divny :D

**Comment by lukasprelovsky** [comment]
Ahoj, novinka z glami. Free rezim pouze s Glami  PiXel

Glami piXel bude povinný pre všetky obchody v neplatenom režime od 1. októbra 2017 

Vážení partneri,

ako sme vám avizovali v našom pravidelnom newsletteri na začiatku septembra, **Glami piXel bude povinný pre všetky obchody v neplatenom režime od 1. októbra 2017.**

**Po tomto dátume budú obchody v neplatenej verzii bez Glami PiXel bohužiaľ pozastavené.**

**Implementujte GLAMI piXel čo najskôr**
Aby mohol systém zhromaždiť dostatok údajov pre hlavnú sezónu. Ak chcete maximalizovať výsledky a zvýšiť návštevnosť, aktivujte aj prednostný režim, ktorý je platený na základe ceny za preklik. 

V prípade, že pracujete na implementácii Glami Pixelu a radi by ste sa vyhli pozastaveniu Vášho obchodu, môžete využiť prednostný režimu. Prednostný platený režim má výhody, ktoré so sebou nesie: vyššiu návštevnosť, možnosť jej optimalizácie na rôznorodé kategórie a po implementácii PiXelu aj sledovanie detailných štatistík. V prednostnom režime môžete priviesť až 5× viac návštevnosti a získať viac objednávok. Kombinácia prednostného režimu a Glami PiXelu vedie k najlepším možným výsledkom: https://partner.glami.sk/s/pixel/.

DÔLEŽITÉ: Pri implementácii sa uistite, že nám zasielate unikátny ItemID v Glami xml feedu a zároveň rovnaké ItemID aj v Glami PiXel.

Ak máte ďalšie otázky, navštívte naše FAQ: http://glami.info/cesky/.

**Comment by lukasprelovsky** [comment]
[glami update for XML glami]

Vážení partneri,

chceli by sme naviazať na náš newsletter z minulého týždňa, kde sme Vás informovali o zavedení nového povinného parametra na GLAMI – materiál, a zodpovedať detailnejšie vaše najčastejšie otázky. Ako sme už spomínali, jedná sa o parameter, ktorý čím ďalej, tým viac zaujíma užívateľov a chceme s ním tak začať aktívne pracovať aj na GLAMI. 

Teší nás, že prví partneri už dokázali nový parameter implementovať. Máme od Vás pozitívne reakcie a veríme, že je to správny krok. Je našou snahou Vám pomôcť a vyjsť v ústrety v zložitejších prípadoch, preto sa na nás neváhajte obrátiť.

XML feed špecifikácia bude vyzerať nasledovne – uvádzajte, prosím, materiál vrátane jeho percentuálneho zastúpenia v produkte:

Príklad produktu z jednej zložky. Typicky: tričká, svetre, mikiny, …
Napríklad tričká sú zvyčajne vyrobené z jednej tkaniny, ktorá sa môže skladať z viacero materiálov. Nie je teda nutné uvádzať názov zložky v <PARAM_NAME> (napr. podšívka, výplň, podrážka, …), stačí uviesť len “materiál”. 

TRIČKO
<PARAM>
<PARAM_NAME>materiál</PARAM_NAME>
<VAL>polyester</VAL>
<PERCENTAGE>20%</PERCENTAGE>
</PARAM>
<PARAM>
<PARAM_NAME>materiál</PARAM_NAME>
<VAL>bavlna</VAL>
<PERCENTAGE>80%</PERCENTAGE>
</PARAM>

Príklady produktov s viacerými zložkami. Typicky: bundy, obuv, batohy, …
V týchto prípadoch parameter <PARAM_NAME>ma­teriál</PARAM_NA­ME> doplňte o názov zložky (napr. podšívka, výplň, podrážka, …), vždy však ponechejte kľúčové slovo „materiál“. Pre každý z nich je nutné uviesť materiál, z ktorého sú vyrobené a percentuálny podiel.

BUNDA
<PARAM>
<PARAM_NAME>materiál podšívka</PARAM_NAME>
<VAL>nylon</VAL>
<PERCENTAGE>50%</PERCENTAGE>
</PARAM>
<PARAM>
<PARAM_NAME>materiál podšívka</PARAM_NAME>
<VAL>polyester</VAL>
<PERCENTAGE>50%</PERCENTAGE>
</PARAM>
<PARAM>
<PARAM_NAME>materiál výplň</PARAM_NAME>
<VAL>perie</VAL>
<PERCENTAGE>100%</PERCENTAGE>
</PARAM>
<PARAM>
<PARAM_NAME>materiál vrch</PARAM_NAME>
<VAL>softshell</VAL>
<PERCENTAGE>100%</PERCENTAGE>
</PARAM>

OBUV
<PARAM>
<PARAM_NAME>materiál podšívka</PARAM_NAME>
<VAL>bavlna</VAL>
<PERCENTAGE>50%</PERCENTAGE>
</PARAM>
<PARAM>
<PARAM_NAME>materiál podšívka</PARAM_NAME>
<VAL>polyester</VAL>
<PERCENTAGE>50%</PERCENTAGE>
</PARAM>
<PARAM>
<PARAM_NAME>materiál podrážka</PARAM_NAME>
<VAL>pryž</VAL>
<PERCENTAGE>100%</PERCENTAGE>
</PARAM>

A teraz už k vašim otázkam:

Bude sa táto zmena týkať iba českého/slovenského či všetkých GLAMI?
Zavedenie povinného materiálu platí pre GLAMI na všetkých trhoch okrem Francúzska a Nemecka. 

Pre aké kategórie bude materiál a jeho percentuálne zastúpenie povinné?
V prvej fáze to bude povinné pre kategórie oblečenie, obuv a doplnky tak, ako je uvedené v príkladoch vyššie. Detailné informácie o materiáloch vždy pomáhajú zákazníkom pri nakupování. Ak máte otázky ohľadom špecifickej kategórie, dajte nám vedieť, pomôžeme Vám nájsť spoločné najlepšie riešenie.

Je treba posielať informácie o materiáli v lokálnom jazyku či anglicky?
V GLAMI sa snažíme byť čo najviac lokálni pre zákazníkov aj partnerov v danej zemi, informácie tak pokiaľ možno uvádzajte vždy v lokálnom jazyku daného GLAMI. Pokiaľ z nejakého dôvodu je pre Vás lepšia angličtina, dajte nám vedieť, skúsime Vám vyjsť v ústrety, pokiaľ to bude čo i len trochu možné.

Môžete pracovať aj s iným než GLAMI formátom, kde napr. percentuálne zastúpenie nerozdelíme do zvlášť tagov, ale zlúčime ich do jedného – <VAL>50% polyester, 50% bavlna</VAL>?
Prosím, posielajte nám ideálne hodnoty podľa našich špecifikácií vyššie. Pri veľkom množstve produktov a partnerov sa v prípade iného formátu môže stať, že se dáta nespracujú a nezobrazia správne. 

Nemáme dané informácie od nášho dodávateľa, čo s tým?
Informácie o materiáli budú zákazníkmi vyžadované čím ďalej, tým viac, pýtajte sa tak vašich dodávateľov a vyžadujte od nich tieto informáce. Rozumieme však, že to môže chvíľu trvať. Ak očakáváte oneskorenie v implementácii vo vašom e-shope, dajte nám, prosím, vedieť.

Nakoľko presnú informáciu o materiáli je potreba uvádzať – stačí len “textil” či je potreba rozlišovať podrobnejšie?
Čím presnejšie informácie o danom materiáli uvediete, tým lepšie. Rozlišujte teda čo nejpodrobnejšie môžete. V prípade “textilu” teda napr. na polyester, nylon apod.

Do budúcna plánujeme tiež spustenie prehľadného prievodcu materiálmi pre užívateľov, budeme Vás o tom včas informovať. Pripomíname zároveň, že produkty bez uvedeného materiálu a percentuálneho zastúpenia prestaneme na GLAMI zobrazovať od 1.8.2019, uistite sa preto, že tieto informáce vo feede do tej doby máte. 

V prípade ďalších otázok či nejasností sa na nás neváhajte obrátiť.

Denis

**Comment by pavelevap** [comment]
@lukasprelovsky: To by mělo být možné bez problémů nastavit pomocí vlastní definice parametrů (viz #70)?
