### ISSUE TITLE
Chyba v class-ceske-sluzby-admin.php na riadku 400 (platba prevodom na učet nie je zapnuta)

### ISSUE THREAD

**Issue by jasomdotnet** [pavelevap/ceske-sluzby#204]
Takúto škaredú chybu dostanem v admine ked nie je zapnutá platba na účet. Platiť sa dá len cez dobierku.

```
Notice: Undefined index: bacs in /var/www/stranka.sk/htdocs/wp-content/plugins/ceske-sluzby/includes/class-ceske-sluzby-admin.php on line 400

Warning: Creating default object from empty value in /var/www/stranka.sk/htdocs/wp-content/plugins/ceske-sluzby/includes/class-ceske-sluzby-admin.php on line 400

Notice: Undefined property: stdClass::$form_fields in /var/www/stranka.sk/htdocs/wp-content/plugins/ceske-sluzby/includes/class-ceske-sluzby-admin.php on line 400

Fatal error: Uncaught Error: Unsupported operand types in /var/www/stranka.sk/htdocs/wp-content/plugins/ceske-sluzby/includes/class-ceske-sluzby-admin.php:400 Stack trace: #0 /var/www/stranka.sk/htdocs/wp-includes/class-wp-hook.php(286): WC_Settings_Tab_Ceske_Sluzby_Admin::ceske_sluzby_nastaveni_plateb('') #1 /var/www/stranka.sk/htdocs/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #2 /var/www/stranka.sk/htdocs/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #3 /var/www/stranka.sk/htdocs/wp-settings.php(546): do_action('wp_loaded') #4 /var/www/stranka.sk/wp-config.php(87): require_once('/var/www/strank...') #5 /var/www/stranka.sk/htdocs/wp-load.php(42): require_once('/var/www/strank...') #6 /var/www/stranka.sk/htdocs/wp-admin/admin.php(34): require_once('/var/www/strank...') #7 /var/www/stranka.sk/htdocs/wp-admin/index.php(10): require_once('/var/www/strank...') #8 {main} thrown in /var/www/stranka.sk/htdocs/wp-content/plugins/ceske-sluzby/includes/class-ceske-sluzby-admin.php on line 400
```

**Comment by pavelevap** [comment]
Díky, opraveno.
