### ISSUE TITLE
České služby a WooCommerce Table Rate Shipping

### ISSUE THREAD

**Issue by novetrendy** [pavelevap/ceske-sluzby#210]
Dobrý den při použití pluginu **WooCommerce Table Rate Shipping** vyskočí následující chyba:
```
[09-Jan-2020 06:45:55 UTC] PHP Notice:  Undefined variable: shipping_method in .../moduly/ceske-sluzby-master/ceske-sluzby.php on line 2018
[09-Jan-2020 06:45:55 UTC] PHP Fatal error:  Uncaught Error: Call to a member function is_taxable() on null in .../ceske-sluzby-master/ceske-sluzby.php:2018
Stack trace:
#0 .../wp-includes/class-wp-hook.php(288): ceske_sluzby_doprava_cenove_intervaly(Array)
#1 .../wp-includes/plugin.php(208): WP_Hook->apply_filters(Array, Array)
#2 .../woocommerce/includes/class-wc-shipping.php(339): apply_filters('woocommerce_pac...', Array, Array)
#3 .../woocommerce/includes/class-wc-shipping.php(258): WC_Shipping->calculate_shipping_for_package(Array, 0)
#4 .../woocommerce/includes/class-wc-cart.php(1259): WC_Shipping->calculate_shipping(Array)
#5 .../woocommerce/includes/class-wc-cart-totals.php(345): WC_Cart->calculate_shipping()
#6 /usr/lo in .../ceske-sluzby-master/ceske-sluzby.php on line 2018
```

Pokud dám na první místo v dopravě nějakou standardní metodu (třeba Místní vyzvednutí), tak se chyba neprojeví.

**Comment by pavelevap** [comment]
Hmmm, chyba odkazuje na tento řádek: https://github.com/pavelevap/ceske-sluzby/blob/cc428c33d02261011ee0e3289eb8675a74adad63/ceske-sluzby.php#L2018

Podle toho to vypadá, že používáte (nebo máte aktivované) nastavení cenových intervalů pro dopravu v rámci pluginu České služby? Je potom potřeba používat i plugin WooCommerce Table Rate Shipping (měl by dělat podobnou funkci)?

Podívám se na to, plugin patrně používá něco trochu jinak než je očekáváno (testoval jsem jen standardní dopravní metody WooCommerce a pluginu České služby).

**Comment by novetrendy** [comment]
Ano mám aktivovaný cenový interval. Nicméně musím používat i Table Rate Shipping, protože se doprava počítá i podle hmotnosti košíku.
