### ISSUE TITLE
Chyba - Dostupné platební metody

### ISSUE THREAD

**Issue by vvvamik** [pavelevap/ceske-sluzby#215]
Když ve Woocommerce > Nastavení > Doprava > Zóny dopravy > Dopravní metody nastavím Dostupné dopravní metody začne se hlásit tato chyba ve Stavu webu.

REST API je jeden ze způsobů, jak WordPress a další aplikace komunikují se serverem. Jedním z příkladů je obrazovka editoru, která se o toto API opírá při zobrazování a ukládání příspěvků a stránek.

Volání REST API vrátilo následující neočekávaný výsledek: (500)
Fatal error: Uncaught Error: Call to a member function get() on null in /wp-content/plugins/ceske-sluzby-master/includes/ceske-sluzby-functions.php:613 Stack trace: #0 /wp-content/plugins/ceske-sluzby-master/ceske-sluzby.php(1793): zkontrolovat_nastavenou_hodnotu('', Array, '', 'platebni_metody', 'ceske_sluzby_pl...') #1 /wp-includes/class-wp-hook.php(287): ceske_sluzby_dostupne_platebni_metody(Array) #2 /wp-includes/plugin.php(206): WP_Hook->apply_filters(Array, Array) #3 /wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(160): apply_filters('woocommerce_ava...', Array) #4 /wp-content/plugins/ceske-sluzby-master/ceske-sluzby.php(2069): WC_Pay in /wp-content/plugins/ceske-sluzby-master/includes/ceske-sluzby-functions.php on line 613

Na webu došlo k závažné chybě.

**Comment by uhlhosting** [comment]
Mam uplne to samej problem, kdyz to pouzivam spolecne s WooCommerce multilingual, a PayU plugin. Da se videt v site Health, ze je neco co blokuje REST API.

**Comment by vvvamik** [comment]
@pavelevap 
A stejný problém při nastavení Woocommerce > Nastavení > Doprava > Zóny dopravy > Dopravní metody nastavím Dostupné dopravní metody, blokuje Woocommerce Stock Manager.

<a href="https://ibb.co/kg2rzR1"><img src="https://i.ibb.co/Z6zwvnm/stock.jpg" alt="stock" border="0"></a>

Upozornění v konzoli:
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”.

Error:
/wp-json/wc/v3/products?per_page=50
